services:
  db:
    image: mysql:8.0
    container_name: fw-mysql
    environment:
      MYSQL_DATABASE: todoapp
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - fw-db-data:/var/lib/mysql

volumes:
  fw-db-data:
